version: "3.1"

services:
  globitokukiapp:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_PROFILES_ACTIVE: prod
      GLOBITOKUKI_PIN: ${GLOBITOKUKI_PIN}
    ports:
      - "8080:8080"
  
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - globitokukiapp
