APP_PRODUCTION: true
FRONTEND_URL1: https://globitokuki.vercel.app
FRONTEND_URL2: https://globitokuki.site

spring:
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB
  datasource:
    url: jdbc:postgresql://postgresdb:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maxLifetime: 150000
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format-sql: true

REDIS_HOST: ${REDIS_HOST}
REDIS_PORT: ${REDIS_PORT}
REDIS_PASSWORD: ${REDIS_PASSWORD}

JWT_SECRET_KEY: ${JWT_SECRET_KEY}
JWT_EXP_TIME: ${JWT_EXP_TIME}

server:
  port: 8080
